web_app/models.py
from mongoengine import Document, StringField, IntField, ListField, FloatField, EmbeddedDocument, EmbeddedDocumentField, URLField

class Reply(EmbeddedDocument):
    comment_id = StringField(required=True)
    author = StringField(default="[deleted]")
    body = StringField(default="[deleted]")
    compound_sentiment = FloatField()
    neg_sentiment = FloatField()
    neu_sentiment = FloatField()
    pos_sentiment = FloatField()
    vader_classification = StringField()
    distilbert_sentiment = StringField()
    distilbert_confidence = FloatField(default=0.0)
    utc_created = IntField()

    replies = ListField(EmbeddedDocumentField("Reply"))

class Comment(EmbeddedDocument):
    comment_id = StringField(required=True)
    author = StringField(default="[deleted]")
    body = StringField(default="[deleted]")
    compound_sentiment = FloatField()
    neg_sentiment = FloatField()
    neu_sentiment = FloatField()
    pos_sentiment = FloatField()
    vader_classification = StringField()
    distilbert_sentiment = StringField()
    distilbert_confidence = FloatField(default=0.0)
    utc_created = IntField()

    replies = ListField(EmbeddedDocumentField(Reply))

class Post(Document):
    post_id = StringField(required=True, unique=True)
    title = StringField(required=True)
    author = StringField(default="[deleted]")
    score = IntField(default=0)
    avg_neg = FloatField()
    avg_neu = FloatField()
    avg_pos = FloatField()
    avg_compound = FloatField()
    neg_count = IntField()
    neu_count = IntField()
    pos_count = IntField()
    vader_post_classification = StringField()
    distilbert_neg_count = IntField()
    distilbert_pos_count = IntField()
    distilbert_avg_confidence = FloatField()
    distilbert_post_classification = StringField()
    total_bodies = IntField()
    url = URLField()
    utc_created = IntField()

    comments = ListField(EmbeddedDocumentField(Comment))

    meta = {
        "collection": "post_game_threads",
        "indexes": [
            {"fields": ["post_id"], "unique": True},
            {"fields": ["title"]},
            {"fields": ["author"]},
            {"fields": ["-utc_created"]}
        ]
    }

web_app/__init__.py
from flask import Flask
from mongoengine import connect
import configparser
import os
from dotenv import load_dotenv

def create_app():

    app = Flask(__name__)

    load_dotenv()

    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    config = configparser.ConfigParser()
    config.read(os.path.join(project_root, "config.ini"))

    Mongo_uri = None

    if os.getenv("DEPLOYMENT_MONGO_URI"):
        Mongo_uri = os.getenv("DEPLOYMENT_MONGO_URI")
        print("Connecting to MongoDB via DEPLOYMENT_MONGO_URI environment variable.")
    elif config.has_section("MongoDB") and config.has_option("MongoDB", "uri"):
        Mongo_uri = config.get("MongoDB", "uri")
        print("Connecting to Local MongoDB via config.ini")
    else:
        raise ValueError("Error in Connecting to MongoDB")

    app.config["MONGODB_SETTINGS"] = {
        "host": Mongo_uri,
        "db": "canucks_reddit_data",
        "alias": "default",
        "uuidRepresentation": "standard"

    }

    connect(**app.config["MONGODB_SETTINGS"])

    from .routes import bp
    app.register_blueprint(bp)

    return app

web_app/routes.py
from flask import Blueprint, render_template, url_for
from .models import Post, Comment, Reply
from .graphics.dual_sentiment import sentiment_distribution
from .graphics.sentiment_proportions import draw_pie_chart

bp = Blueprint("main", __name__)

@bp.route('/')
def index():
    return render_template("home_page.html")

@bp.route('/posts')
def list_posts():
    all_posts = Post.objects().only( # type: ignore
        'title', 'post_id', "total_bodies", 
        "vader_post_classification", "distilbert_post_classification")
    
    return render_template("list_posts.html", posts=all_posts)

@bp.route('/posts/<string:post_id>')
def post_detail(post_id):
    post = Post.objects(post_id=post_id).first() # type: ignore
    post_title = post.title.replace("Post Game Thread: ", "")

    if post:
        return render_template("post_detail.html", post=post, clean_title=post_title)
    else:
        return "Post Not Found!", 404
    
@bp.route('/visualize')
def draw_graphs():
    all_posts = Post.objects().only('title', 'post_id', "total_bodies", # type: ignore
        "pos_count", "neu_count", "neg_count","utc_created",
        "distilbert_pos_count", "distilbert_neg_count") 
    
    chart1 = sentiment_distribution(all_posts)
    chart2 = draw_pie_chart(all_posts)
    return render_template("visualizations.html", chart_one=chart1, chart_two = chart2)

web_app/templates/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Canucks Sentiment</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='home_page.css') }}">
</head>
<body>
    <header class="project-header">
        <h1>Canucks Sentiment Analysis</h1>
        <ul>
            <li><a href="{{ url_for('main.list_posts') }}">All Posts</a></li>
        </ul>
    </header>
    <div>
        <h2>Welcome to Canucks Sentiment Analysis! Checkout the analysis by clicking the All Posts button above!</h2>
    </div>
    <div class="paragraph">
        <h2>
            What this is and why I made it 
        </h2>
        <p>
            This app analyzes post-game threads from the r/canucks subreddit to understand how fans react after each game. 
            I specifically targeted post-game threads because they reflect the immediate response of fans who actively watched the games.
            It currently uses two different sentiment analysis models to classify the sentiment of each comment, as well as the overall tone of each thread.
            The All Posts page contains 62 post-game threads from the 2024–25 NHL season, each with its own sentiment breakdown. Every comment is displayed alongside 
            its sentiment classification, giving a picture of how fans responded after each game.
        </p>
        <p>
            I became invested in the Vancouver Canucks again during the 2023–24 season after their strong start to the regular season and have been 
            following them since. Having lived in BC all my life, I never fully got into the team after what happened in 2011. But ever since two 
            seasons ago, I’ve made it a habit to catch every game on TV if I can and became a frequent visitor of the r/canucks subreddit.
            Since the team was doing so well in the 2023–24 season, I noticed that many comments and posts were positive. But starting with the 
            2024–25 season and continuing throughout, I began to notice a trend of negative comments and posts appearing on the subreddit. So I thought 
            there was potential to work on my data science skills and to combine it with my Canucks fandom in one project.
        </p>
        <p>
            This project started as an exercise in using the PRAW API to collect post-game threads and storing non-tabular data in MongoDB. 
            I knew I wanted to analyze the data I was collecting and explore natural language processing, then eventually I realized I wanted a way to 
            showcase my work beyond a GitHub repo which was why I made this Flask app to display the threads and sentiment results with a simple UI.
            In the future, I plan to add a sarcasm classfier, graphs/visualizations, and a player mention tracker. 
        </p>
    </div>
    <div class="paragraph">
        <h2>Sentiment Analysis Models</h2>
        <p>Each thread and every comment within is scored by both models, and the results are displayed together for easy comparison.</p>
        <div>
        <p>
            <strong>VADER</strong> (Valence Aware Dictionary and sEntiment Reasoner) is a pre-trained sentiment analysis tool designed for short, 
            informal text like social media posts or reviews. It is part of <strong>NLTK</strong> (Natural Language Toolkit), a popular 
            Python library for natural language processing.
        </p>

        <p>
            It is <em>rule-based</em>, meaning it uses a predefined set of lingustic rules and a sentiment dictionary with predetermined scores
            rather than machine learning to evaluate text. It accounts for punctuation, capitalization, degree modifiers such as "very", and negations. 
            For each text, it returns four scores: <strong>positive</strong>, <strong>neutral</strong>, and <strong>negative</strong> 
            each indicating the proportion of sentiment in the text that belongs with each category, and a <strong>compound score</strong> from 
            -1 to +1 summarizing overall sentiment.
        </p>

        <p>
            Sentiment classification is based on the compound score using these standard thresholds:
        </p>
        <ul>
            <li><strong>Compound ≥ 0.05</strong>: Positive</li>
            <li><strong>Compound ≤ -0.05</strong>: Negative</li>
            <li><strong>Between -0.05 and 0.05</strong>: Neutral</li>
        </ul>
        </div>
        <div>
            <p>
                <strong>DistilBERT</strong> is a smaller, faster version of <strong>BERT</strong> (Bidirectional Encoder Representations from Transformers), 
                a pre-trained state-of-the-art language model developed by Google. DistilBERT retains over 95% of BERT’s performance while being 40% smaller and 
                60% faster, making it well-suited for real-time applications like this one.
            </p>
            <p>
                Unlike VADER, which is rule-based, <strong>DistilBERT</strong> is a <em>deep learning model</em> trained on large amounts of text data. It uses a  
                transformer architecture to understand the context and meaning of words in a sentence, allowing it to capture more nuanced sentiment, especially
                in longer or more complex comments.
            </p>
            <p>
                For each text, DistilBERT returns:
            </p>
            <ul>
                <li><strong>Sentiment Label:</strong> Positive or Negative</li>
                <li><strong>Confidence Score:</strong> Between 0 and 1, the model's certainty in its prediction</li>
            </ul>
        </div>
    </div>
    <div class="paragraph">
        <h2>Limitations</h2>
        <p>
            While both <strong>VADER</strong> and <strong>DistilBERT</strong> offer useful generalized insights, they also have some known drawbacks.
        </p>
        <ul>
            <li>Comments/replies can often be misclassified due to their differing lengths, sarcasm, or reliance on context from the parent comment/post</li>
            <li>Sarcasm and irony are difficult for both models to detect, especially in emotionally charged or joking comments</li>
            <li>No game context means the models analyzes the text in isolation  and can’t account for what actually happened during the game</li>
            <li>Mixed-tone comments such as “We were awful, but at least this player showed up” often get flattened into a single label</li>
            <li>DistilBERT confidence scores can be misleading on short or vague comments, especially replies</li>
        </ul>
        <p>
            These limitations are part of what makes this project interesting and I’m exploring ways to extract additional insights in future updates.
        </p>
    </div>
    <div class="paragraph">
        <h2>More Technical Information</h2>
        <p>
            For more technical information including the source code, technologies used, data collection scripts, and sentiment analysis scripts please check here:
            <ul>
                <li><a href="https://github.com/ericcheung1/canucks_reddit_proj" target="_blank", rel="noopener noreferrer">GitHub Repository</a></li>
            </ul>
        </p>
    </div>


</body>
</html>

web_app/templates/list_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Canucks Sentiment: All Posts</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='list_posts.css') }}">
</head>
<body>
    <header class="project-header">
        <h1>Canucks Sentiment Analysis</h1>
        <ul>
            <li><a href="{{ url_for('main.index') }}">Home</a></li>
        </ul>
    </header>
    <div class="post-feed">
        <h2>
            Model Summary Graph
        </h2>
        <div class="reddit-post">
            <div class="post-title">
                <a href="{{ url_for('main.draw_graphs') }}">
                    Sentiment Trends for Vancouver Canucks
                </a>
                <div class="post-meta">
                    2 Graphs
                </div>
            </div>
        </div>
        <h2>
            Post Game Threads from the 2024-25 NHL Season
        </h2>
        <div>
            {% for post in posts %}
                <div class="reddit-post">
                    <div class="post-title">
                        <a href="{{ url_for('main.post_detail', post_id=post.post_id) }}">
                            {{ post.title.replace("Post Game Thread: ", "") }} 
                        </a>
                    </div>
                    <div class="post-meta">
                        <ul>
                            <li>{{ post.total_bodies }} comments ||</li> 
                            <li>VADER:
                                <span class="{% if post.vader_post_classification == 'POSITIVE' %}POS-SENTIMENT
                                {% elif post.vader_post_classification == 'NEGATIVE' %}NEG-SENTIMENT
                                {% elif post.vader_post_classification == 'NEUTRAL' %}NEU-SENTIMENT{% endif %}">
                                {{ post.vader_post_classification }}</span> ||
                            </li>
                            <li>DistilBERT: 
                                <span class="{% if post.distilbert_post_classification == 'POSITIVE' %}POS-SENTIMENT
                                {% elif post.distilbert_post_classification == 'NEGATIVE' %}NEG-SENTIMENT
                                {% elif post.distilbert_post_classification == 'NEUTRAL' %}NEU-SENTIMENT{% endif %}">
                                {{ post.distilbert_post_classification }}</span> ||
                            </li>
                        </ul>
                    </div>
                </div>
            {% else %}
                <div>No posts found. (Is your MongoDB running and data collected?)</div>
            {% endfor %}
        </div>
    </div>   
</body>
</html>

web_app/templates/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Canucks Sentiment: {{ clean_title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='post_detail.css') }}">
</head>
<body>
    <header class="project-header">
        <h1>Canucks Sentiment Analysis</h1>
        <ul>
            <li><a href="{{ url_for('main.index') }}">Home</a></li>
            <li><a href="{{ url_for('main.list_posts') }}">All Posts</a></li>
        </ul>
    </header>
    <div>
        <h1>{{ clean_title }}</h1>

        <h3>Sentiment Analysis</h3>

        <div class="sentiment-div">
        <div>
            <h3>Overall Classification and Scores for Post</h3>
        <ul class="sentiment-box">
            <li>
                <p>
                    <strong>VADER Sentiment Results: </strong>
                    Classification: 
                    <span class="{% if post.vader_post_classification == 'POSITIVE' %}POS-SENTIMENT
                    {% elif post.vader_post_classification == 'NEGATIVE' %}NEG-SENTIMENT
                    {% elif post.vader_post_classification == 'NEUTRAL' %}NEU-SENTIMENT{% endif %}">
                    {{ post.vader_post_classification }}</span> ||
                    Positive Comments: <strong>{{ post.pos_count }}</strong> ||
                    Neutral Comments: <strong>{{ post.neu_count }}</strong> ||
                    Negative Comments: <strong>{{ post.neg_count }}</strong> ||
                </p>
                <p>
                    <strong>VADER Scores:</strong>
                    Mean Compound: <strong>{{ post.avg_compound | round(3) }}</strong> ||
                    Mean Positive: <strong>{{ post.avg_pos | round(3) }}</strong> ||
                    Mean Neutral: <strong>{{ post.avg_neu | round(3) }}</strong> ||
                    Mean Negative: <strong>{{ post.avg_neg | round(3) }}</strong> ||
                </p>
            
            </li>
            <li>
                <p>
                    <strong>DistilBERT Sentiment Results: </strong> 
                    Classification: 
                    <span class="{% if post.distilbert_post_classification == 'POSITIVE' %}POS-SENTIMENT
                    {% elif post.distilbert_post_classification == 'NEGATIVE' %}NEG-SENTIMENT
                    {% elif post.distilbert_post_classification == 'NEUTRAL' %}NEU-SENTIMENT{% endif %}">
                        {{ post.distilbert_post_classification }}</span> ||
                    Positive Comments: <strong>{{ post.distilbert_pos_count }}</strong> ||
                    Negative Comments: <strong>{{ post.distilbert_neg_count }}</strong> ||
                </p>
            </li>
            <li>
                <p>
                    <strong>DistilBERT Score:</strong>
                    Mean Confidence Score: <strong>{{ post.distilbert_avg_confidence | round(3) }}</strong> ||
                </p>
            </li>
        </ul>
        </div>
        <div>
            <h3>Model Details and Interpretation </h3>
            <ul class="sentiment-box">
                <li>
                    <p>
                        <strong>VADER</strong> is a rules-based model that calculates sentiment and returns four scores: positive, 
                        neutral, negative, and compound which represents proportion of each sentiment category in the comment or thread.
                        A 0.15 positive score means that 15% of the comment contains positive sentiment. The compound score is a normalized overall score 
                        from -1 meaning very negative to +1 meaning very positive. Sentiment Classification is based on the compound score: greater than 
                        or equal to 0.05 is positive, less than or equal to -0.05 is negative, and between -0.05 and 0.05
                        is neutral.
                    </p>

                </li>
                <li>
                    <p>
                        <strong>DistilBERT</strong> is a deep learning model that classfies text into <em>positive</em> or <em>negative</em>, 
                        and assigns a <em>confidence score</em> to each prediction, ranging from <em>0 indicating no confidence</em> to <em>1 indicating 
                        full confidence</em>. If a text is labeled <em>positive</em> with a confidence of <em>0.92</em>, it means the model is 92% confident
                        that the sentiment is positive. Posts are classified as neutral if there are equal number of postive and negative comments.
                    </p>
                </li>
                <li>
                    <p>
                        Sentiment classifications may be inaccurate, especially for short replies, sarcastic comments, or posts lacking context. 
                        Both models analyze text in isolation and can miss nuance.
                    </p>
                </li>
            </ul>
        </div>
        </div>

        <p><strong>Score:</strong> 
            <a href="https://www.google.com/search?q={{ clean_title|urlencode }}" target="_blank", rel="noopener noreferrer">View Score</a>
        </p>

        <h3>Comments: Total {{ post.total_bodies }} (Warning: Reddit Comments May Contain Swearing or Explicit Language)</h3>
        
        <div class="comment-div">
        {% macro render_comments(comments, level) %}
            <ul class="comment-list">
            {% for comment in comments %}
                <li class="comment-item comment-level-{{ level }}">
                    <p><span class="comment-author">{{ comment.author or "[deleted]" }}:</span> {{ comment.body }}</p>

                    <div class="comment-item sentiment-box">
                        <ul>
                            <li>
                                <p>
                                    <strong>VADER Analysis:</strong>
                                    Classification: 
                                    <span class="{% if comment.vader_classification == 'POSITIVE' %}POS-SENTIMENT
                                    {% elif comment.vader_classification == 'NEGATIVE' %}NEG-SENTIMENT
                                    {% elif comment.vader_classification == 'NEUTRAL' %}NEU-SENTIMENT{% endif %}">
                                        {{ comment.vader_classification }}</span> ||
                                    Compound: <strong>{{ comment.compound_sentiment | round(3) }}</strong> || 
                                    Positive: <strong>{{ comment.pos_sentiment | round(3) }}</strong> || 
                                    Neutral: <strong>{{ comment.neu_sentiment | round(3) }}</strong> || 
                                    Negative: <strong>{{ comment.neg_sentiment | round(3) }}</strong> || 
                                </p>
                            </li>
                            <li>
                                <p>
                                    <strong>DistilBERT Analysis:</strong>
                                    Classification: 
                                    <span class="{% if comment.distilbert_sentiment == 'POSITIVE' %}POS-SENTIMENT
                                    {% elif comment.distilbert_sentiment == 'NEGATIVE' %}NEG-SENTIMENT
                                    {% elif comment.distilbert_sentiment == 'NEUTRAL' %}NEU-SENTIMENT{% endif %}">
                                        {{ comment.distilbert_sentiment }}</span> ||
                                    Confidence Score: <strong>{{ comment.distilbert_confidence | round(3) }}</strong> ||
                                </p>
                            </li>
                        </ul>
                    </div>

                    {% if comment.replies %}
                        {{ render_comments(comment.replies, level + 1) }}
                    {% endif %}
                </li>
            {% endfor %}
            </ul>
        {% endmacro %}

        {% if post.comments %}
            {{ render_comments(post.comments, 0 ) }}
        {% else %}
            <p>No Comments found for this post.</p>
        {% endif %}

        <p style="margin-top: 20px;"><a href="{{ url_for('main.list_posts') }}">Back to All Posts</a></p>
        </div>
    </div>
</body>
</html>

web_app/templates/visualizations.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport", content="width=device-width initial-scale=1.0">
    <title>Canucks Sentiment: Visualizations</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='visualizations.css') }}">
</head>
<body>
    <header class="project-header">
        <h1>Canucks Sentiment Analysis</h1>
        <ul>
            <li><a href="{{ url_for('main.index') }}">Home</a></li>
            <li><a href="{{ url_for('main.list_posts') }}">All Posts</a></li>
        </ul>
    </header>

    <div class="post-feed">
        <h2>Number of Comments Per Thread</h2>
        <div class="reddit-post-chart">
            <div class="reddit-post-header"></div>
            {{ chart_one | safe}}
        </div>
        <h2>Pie Chart</h2>
        <div class="reddit-post-chart">
            <div class="reddit-post-header"></div>
            {{ chart_two | safe}}
        </div>
    </div>
</body>
</html>